export default [
  { name: 'Монгол хэл', enName: 'Mongolian', code: 'mn' },
  { name: 'বাংলা', enName: 'Bengali', code: 'bn' },
  { name: 'हिन्दी', enName: 'Hindi', code: 'hi' },
  { name: '繁體中文', enName: 'Traditional Chinese', code: 'zh-hant' },
  { name: 'Tiếng Việt', enName: 'Vietnamese', code: 'vi' },
  { name: 'Deutsch', enName: 'German', code: 'de' },
  { name: 'Español', enName: 'Spanish', code: 'es' },
  {
    name: 'Français',
    enName: 'French',
    code: 'fr',
    corePages: 'Pages Fondamentales',
    nextSteps: 'Étapes suivantes',
  },
  { name: 'العربية', enName: 'Arabic', code: 'ar' },
  { name: '한국어', enName: 'Korean', code: 'ko' },
{ name: '简体中文', enName: 'Simplified Chinese', code: 'zh-hans' },
 { name: 'Bahasa Indonesia', enName: 'Indonesian', code: 'id' },
{ name: 'Русский', enName: 'Russian', code: 'ru' },
{ name: 'ગુજરાતી', enName: 'Gujarati', code: 'gu' },
{ name: 'Polski', enName: 'Polish', code: 'pl' },
{ name: 'Italiano', enName: 'Italian', code: 'it' },
{ name: 'Nederlands', enName: 'Dutch', code: 'nl' },
{ name: 'Türkçe', enName: 'Turkish', code: 'tr' },
{ name: 'Englisg', enName: 'English', code: 'en' },
]
